kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: traefik-whoami
  name: whoami
  labels:
    app: whoami

spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      # annotations:
      #   consul.hashicorp.com/connect-inject: 'true'
      labels:
        app: whoami
    spec:
      containers:
        - name: whoami
          image: traefik/whoami
          ports:
            - name: web
              containerPort: 80
