version: '3.7'

services:
  agent:
    image: portainer/agent:latest
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - portainer_agent_network
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux

  portainer:
    image: portainer/portainer-ce:latest
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - portainer-data:/data
    networks:
      - portainer_agent_network
      - portainer_public
    ports:
      - 8000:8000
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.portainer_portainer.entrypoints=web"
        - "traefik.http.routers.portainer_portainer.rule=Host(`portainer.example.com`)"
        - "traefik.http.routers.portainer_portainer.middlewares=traefik-https-redirect@file"
        - "traefik.http.routers.portainer_portainer-secure.entrypoints=websecure"
        - "traefik.http.routers.portainer_portainer-secure.rule=Host(`portainer.example.com`)"
        - "traefik.http.routers.portainer_portainer-secure.tls=true"
        - "traefik.http.services.portainer_portainer.loadbalancer.server.port=9000"
        - "traefik.http.routers.portainer_portainer-secure.service=portainer_portainer"
        - "traefik.docker.network=portainer_agent_network"
        - "traefik.http.routers.portainer_portainer-secure.tls.certresolver=myresolver"
      # Edge
        - "traefik.http.routers.edge-sec.rule=Host(`edge.example.com`)"
        - "traefik.http.routers.edge-sec.entrypoints=websecure"
        - "traefik.http.services.edge-sec.loadbalancer.server.port=8000"
        - "traefik.http.routers.edge-sec.service=edge-sec"
        - "traefik.http.routers.edge-sec.tls.certresolver=myresolver"

networks:
  portainer_agent_network:
    external: true
  portainer_public:
    external: true

volumes:
  portainer-data: {}
