FROM ubuntu
ADD ./graylog-msg-script.sh /root/dev/graylog/loadmsg/graylog-msg-script.sh
RUN chmod +x /root/dev/graylog/loadmsg/graylog-msg-script.sh
CMD ["/root/dev/graylog/loadmsg/graylog-msg-script.sh"]
