version: '3.7'
services:
  graylog:
    image: graylog/graylog:4.2
    environment:
      - GRAYLOG_MONGODB_URI=mongodb://Network1_mongodb:27017/graylog
      - GRAYLOG_PASSWORD_SECRET=HepoKockice49258
      - GRAYLOG_ROOT_PASSWORD_SHA2=63a52b702ea2823273b1e7cd10721258543dfea2828357b2986e10156310d692
      - GRAYLOG_HTTP_BIND_ADDRESS=0.0.0.0:9000
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - GRAYLOG_HTTP_EXTERNAL_URI=https://graylog.example.com/  #old http://127.0.0.1:9000/
      - GRAYLOG_WEB_ENDPOINT_URI=https://graylog.example.com/api
      - GRAYLOG_IS_MASTER=TRUE
      - GRAYLOG_REST_URI="http://graylog:9000"
      - GRAYLOG_WEB_LISTEN_URI=https://127.0.0.1:9000 #new  
        #- GRAYLOG_REST_LISTEN_URI=http://127.0.0.1:9000/api #old "http://graylog_graylog:9000"
      - GRAYLOG_REST_TRANSPORT_URI=http://graylog_graylog:9000/" #new= http://127.0.0.1:12900 #old= https://graylog.example.com/api
    volumes:
      - graylog:/usr/share/graylog/data
      - graylogjournal:/usr/share/graylog/data/journal
        # configs:
        #- source: graylog-config
        #target: /usr/share/graylog/data/config/graylog.conf
    networks:
      - Network1
        #- hlattach
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.platform.os == linux
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.graylog.entrypoints=web"
        - "traefik.http.routers.graylog.rule=Host(`graylog.example.com`)"
        - "traefik.http.routers.graylog.middlewares=traefik-https-redirect@file"
        - "traefik.http.routers.graylog-secure.entrypoints=websecure"
        - "traefik.http.routers.graylog-secure.rule=Host(`graylog.example.com`)"
        - "traefik.http.routers.graylog-secure.tls=true"
        - "traefik.http.services.graylog.loadbalancer.server.port=9000"
        - "traefik.http.middlewares.graylog-auth.forwardauth.tls.insecureSkipVerify=true"
        - "traefik.docker.network=Network1"
        - "traefik.http.routers.graylog-secure.tls.certresolver=myresolver"
        - "traefik.http.services.graylog.loadbalancer.sticky=true"
        #- "traefik.http.routers.graylog.middlewares=graylog-header2"
        #- "traefik.http.routers.graylog-secure.middlewares=graylog-header2"
        #- "traefik.http.middlewares.graylog-header2.headers.customrequestheaders.X-Graylog-Server-URL=http://graylog_graylog:9000/"
    ports:
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      #GELF TCP
      - 12201:12201
      #GELF UDP
      - 12201:12201/udp

networks:
  Network1:
    external: true
    #hlattach:
    #external: true

volumes:
  graylog:
  graylogjournal:
  graylog2:

#configs:
  #graylog-config:
  #file: ./server.conf
