version: '3.7'
services:
  mongo:
    image: mongo:4.2

    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
    volumes:
      - mongodb_data:/data/db
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2

    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      replicas: 1
  graylog:
    image: graylog/graylog:4.2.9
    environment:
      - GRAYLOG_PASSWORD_SECRET=HepoKockice49258
      - GRAYLOG_ROOT_PASSWORD_SHA2=63a52b702ea2823273b1e7cd10721258543dfea2828357b2986e10156310d692
      - GRAYLOG_HTTP_EXTERNAL_URI=https://graylog.example.com/
      - GRAYLOG_WEB_ENDPOINT_URI=https://graylog.example.com/
    volumes:
      - graylog_data_config:/usr/share/graylog/data/config
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.platform.os == linux
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.graylog.entrypoints=web"
        - "traefik.http.routers.graylog.rule=Host(`graylog.example.com`)"
        - "traefik.http.routers.graylog.middlewares=traefik-https-redirect@file"
        - "traefik.http.routers.graylog-secure.entrypoints=websecure"
        - "traefik.http.routers.graylog-secure.rule=Host(`graylog.example.com`)"
        - "traefik.http.routers.graylog-secure.tls=true"
        - "traefik.http.services.graylog.loadbalancer.server.port=9000"
        - "traefik.http.middlewares.graylog-auth.forwardauth.tls.insecureSkipVerify=true"
        - "traefik.docker.network=Network1"
        - "traefik.http.routers.graylog-secure.tls.certresolver=myresolver"
    ports:
      # Syslog TCP
      - 514:514
      # Syslog UDP
      - 514:514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp

networks:
  default:
    external:
      name: Network1

volumes:
  mongodb_data:
  graylog_data_config: