version: '3.3'

services:
  dc_registry:
    image: registry:2
    environment:
      - "REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/data"
      - "REGISTRY_AUTH=htpasswd"
      - "REGISTRY_AUTH_HTPASSWD_REALM=Registry"
      - "REGISTRY_AUTH_HTPASSWD_PATH=/run/secrets/password"
      - "REGISTRY_STORAGE_DELETE_ENABLED=true"
    deploy:
      placement:
        constraints:
          - node.hostname == vmi1.contaboserver.net
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.dc_registry.loadbalancer.server.port=5000"
        - "traefik.http.services.dc_registry.loadbalancer.passHostHeader=true"
        - "traefik.http.routers.dc_registry.rule=Host(`registry.example.com`)"
        - "traefik.http.routers.dc_registry.entrypoints=web"
        - "traefik.http.routers.dc_registry.middlewares=traefik-https-redirect"
        - "traefik.http.routers.dc_registry-secure.rule=Host(`registry.example.com`)"
        - "traefik.http.routers.dc_registry-secure.entrypoints=websecure"
        - "traefik.http.routers.dc_registry-secure.tls=true"
        - "traefik.docker.network=Network1"
        - "traefik.http.routers.dc_registry-secure.tls.certresolver=myresolver"
    volumes:
      - datadrive:/data
    secrets:
      - password

secrets:
  password:
    file: ./auth/registry.password



networks:
  default:
    external:
      name: Network1
volumes:
  datadrive:

