version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    volumes:
      - elasticsearch:/usr/share/elastic/data
    environment:
      - node.name=elasticsearch
      - cluster.name=dev
      - transport.host=localhost
      - network.host=127.0.0.1
      - http.host=0.0.0.0
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
     #- 9300:9300
    networks:
      - Network1
    deploy:
      replicas: 1

networks:
  Network1:
    external: true

volumes:  
  elasticsearch:
