version: "3.9"
services:
  msql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: msql
    #    ports:
    #      - "5555:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourS@troHAassword
    deploy:
      placement:
        constraints:
          - node.hostname == vmi1.contaboserver.net
      labels:
        - traefik.enable=true
        - traefik.tcp.routers.msql.rule=HostSNI(`*`)
        - traefik.tcp.routers.msql.tls=false
        - traefik.tcp.routers.msql.service=msql
        - traefik.tcp.routers.msql.entrypoints=mssql
        - traefik.tcp.services.msql.loadbalancer.server.port=1433
    volumes:
      - mssql_data:/var/opt/mssql
networks:
  default:
    external:
      name: Network1
volumes:
  mssql_data:
