version: '3.7'

services:
  mongo1:
    hostname: mongo1
    image: mongo:4.2
    networks:
      - Network1
    ports:
      - 30001:27017 
    restart: always
    command: mongod --replSet hl-mongo-set
  mongo2:
    hostname: mongo2
    image: mongo:4.2
    networks:
      - Network1
    ports:
      - 30002:27017
    restart: always
    command: mongod --replSet hl-mongo-set
  mongo3:
    hostname: mongo3
    image: mongo:4.2
    networks:
      - Network1
    ports:
      - 30003:27017
    restart: always
    command: mongod --replSet hl-mongo-set

  mongoinit:
    image: mongo:4.2 
    depends_on:
      - mongo1
      - mongo2

networks:
  Network1:
    external: true