version: "3.7"

networks:
  azuredevops:
    external: true
services:
  azureself-hosted:
    image: registry.example.com/azureagent-ubuntu-18.04:1373
          #image: registry.dev2.com/azure-vsts-agent:ubuntu-16.04
    environment:
      - AZP_URL=https://example.visualstudio.com
      - AZP_TOKEN=142467217846521642514721426148124128
      - AZP_POOL=Linux
      - AZP_AGENT_NAME=ContaboDev
    networks:
      - azuredevops
    deploy:
      placement:
        constraints:
          - node.labels.node_role==worker
 

