version: '3'

services:
  registry:
    image: registry:2
    restart: always
    environment:
      - "REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/data"
      - "REGISTRY_AUTH=htpasswd"
      - "REGISTRY_AUTH_HTPASSWD_REALM=Registry"
      - "REGISTRY_AUTH_HTPASSWD_PATH=/auth/registry.password"
      - "REGISTRY_STORAGE_DELETE_ENABLED=true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.registry.loadbalancer.server.port=80"
      - "traefik.http.services.registry.loadbalancer.passHostHeader=true"
      - "traefik.http.routers.registry.rule=Host(`registry.example.com`)"
      - "traefik.http.routers.registry.entrypoints=web"
      - "traefik.http.routers.registry.middlewares=traefik-https-redirect"
      - "traefik.http.routers.registry-secure.rule=Host(`registry.example.com`)"
      - "traefik.http.routers.registry-secure.entrypoints=websecure"
      - "traefik.http.routers.registry-secure.tls=true"
        #- "traefik.http.routers.registry-secure.middlewares=traefik-auth"
      - "traefik.docker.network=docker-registry"
      - "traefik.http.routers.registry-secure.tls.certresolver=myresolver"

    volumes:
      - datadrive:/data
      - ./auth:/auth:ro
    networks:
      - docker-registry
    deploy:
      placement:
        constraints:
          - node.hostname ==  vmi1.contaboserver.net
networks:
  docker-registry:
    external: true
volumes:
  datadrive:
