FROM ubuntu
ADD ./graylog-msg-script.sh /root/hlbox/graylog/loadmsg/graylog-msg-script.sh
RUN chmod +x /root/hlbox/graylog/loadmsg/graylog-msg-script.sh
CMD ["/root/hlbox/graylog/loadmsg/graylog-msg-script.sh"]
