version: '3.7'
services:
  mongodb:
    image: mongo:4.2
    volumes:
      - mongodb:/data/db
        #environment:
        #MONGO_INITDB_ROOT_USERNAME: root
        #MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
      - 27018:27018
    networks:
      - Network1
    deploy:
      mode: replicated
      replicas: 1

volumes:
  mongodb:

networks:
  Network1:
    external: true
