version: '3.7'

services:
  mongodb:
    image: mongo:4.2
    volumes:
      - mongodb:/data/db
      #- ./init.sh:/scripts/init.sh
    networks:
      - Network1
    ports:
      - 27017:27017
    links:
      - mongodb2
      - mongodb3
    #deploy:
      #replicas: 3
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
  mongodb2:
    image: mongo:4.2
    volumes:
      - mongodb:/data/db
    networks:
      - Network1
    ports:
      - 27018:27017
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
  mongodb3:
    image: mongo:4.2
    volumes:
      - mongodb:/data/db
    networks:
      - Network1
    ports:
      - 27019:27017
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

volumes:
  mongodb:

networks:
  Network1:
    external: true
